services:
    app:
        build: .
        container_name: chatuu-server
        restart: always
        ports:
            - "5000:5000"
        environment:
            DATABASE_URL: "postgresql://postgres:91101@db:5432/chatuu?schema:public"
            REDIS_URL: "redis://redis:6379"

            CLIENT_URL: "http://localhost:3000"

            JWT_SECRET: ""

            GOOGLE_CLIENT_ID: ""
            GOOGLE_CLIENT_SECRET: ""
            GOOGLE_CALLBACK_URL: "http://localhost:5000/api/auth/callback/google"
        depends_on:
            - db
            - redis
        volumes:
            - .:/app
            - /app/node_modules
    db:
        image: postgres:15
        container_name: postgres-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 91101
            POSTGRES_DB: chatuu
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "5050:80"
        depends_on:
            - db

    redis:
        image: redis:7
        container_name: redis-server
        ports:
            - "6379:6379"

volumes:
    postgres_data:
